### ISSUE TITLE
Problems with viewport on mobile devices

### ISSUE THREAD

**Issue by jonivar** [kadekjayak/jquery-PhotoSwipe#1]
Hi

When using with `<meta name="viewport" content="width=device-width, initial-scale =1.0"> `in the `<head>` section on ios (and Windows 10 mobile), the page locks up. See http://geilofjellandsby.no/galleritest/.

This is not an issue on http://photoswipe.com/ which has the same viewport.

Best regards
Jon Ivar

**Comment by kadekjayak** [comment]
Hi Jonivar,

i did a remote debug on my device (Android) and found that same problem..
it seems that the function `_equalizePoints` on photoswipe cause this error, the variable is undefined when that meta viewport is enabled. i didn't try it with the original photoswipe yet.

i will try to check the problem, Thanks for submiting this Issue.. :)

**Comment by jonivar** [comment]
Hi

Any progress on this issue?

:o) Jon Ivar

**Comment by kadekjayak** [comment]
Hi @jonivar 

i little bit busy IRL..
im sorry about it...

it caused by "responsive" option on my code,
adding `width` and `height` attribute on `<img>` tag may fix the issue, 
but i realized now that was a bad idea, i should get `width` and `height` from `data-` attribute

i push an update for your issue, you can check it on repo.. :)

Thanks for your Feedback...
